### ISSUE TITLE
Investigation Auth

### ISSUE THREAD

**Issue by AchinthaHarshamal** [Oral-Cavity-Research/OCR-Spring-Backend#86]
- [ ] Authentication & Authorization
- [ ] Encryption => Asymmetric, Symmetric (Main Encryption algo)
- [ ] AES
- [ ] Digestion in hashing 
- [ ] Hashing (Properties, Main Hashing algo)
- [ ] Digital signature
- [ ] Session token, Auth Token, Refresh token
- [ ] JWT token
- [ ] Session Storage, Cookies
- [ ] User name, password login (step) 
- [ ] Oauth, OAuth 2
- [ ] Sign in with Google
